config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:index, :show]
  resources :subjects, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :user_tasks, only: :update
  resources :user_subjects, only: :update

  namespace :supervisor do
    resources :users
    
    resources :courses do
      resource :assign_trainees
    end

    resources :subjects do
      resources :tasks
    end
    root 'users#index'
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :subject
  has_many :user_tasks
  
  validates :title, presence: true
  validates :content, presence: true
end

app/views/tasks/_task.html.erb
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="headingOne">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#<%= task.id %>"  aria-expanded="true" aria-controls="collapseOne">
        <%= task.title %>
      </a>
    </h4>
  </div>
  <div id="<%= task.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
    <div class="panel-body">
      <% user_task = user_task current_user.id, task.id %>
      <%= task.content %>
      <% unless user_task.status == t(:completed) %>
        <%= link_to t(:finish), user_task_path(user_task, status: t(:completed)), 
                              method: :patch, remote: true, class: "user-task-status btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>