config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:index, :show]
  resources :subjects, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :user_tasks, only: :update
  resources :user_subjects, only: :update

  namespace :supervisor do
    resources :users
    
    resources :courses do
      resource :assign_trainees
    end

    resources :subjects do
      resources :tasks
    end
    root 'users#index'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :course_users, dependent: :destroy
  has_many :courses, through: :course_users
  has_many :activities
  has_many :user_subjects
  has_many :user_tasks

  scope :not_in_a_course, ->{where("supervisor = 'f' AND id NOT IN (SELECT user_id FROM course_users)")}

  before_save {self.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 50},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 5},
                       on: :create
  validates :password, confirmation: true, allow_blank: true

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes! remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes! remember_digest: nil
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/supervisor/assign_trainees_controller.rb
class Supervisor::AssignTraineesController < ApplicationController
  def show
    @course = Course.find params[:course_id]
    @trainees_in_this_course = @course.users
    @no_course_users = User.not_in_a_course.all
  end

  def update
    @course = Course.find params[:course_id]
    if @course.update_attributes course_params
      redirect_to supervisor_course_path(@course)
    else
      render 'assign_trainees'
    end
  end

  private
  def course_params
    params.require(:course).permit user_ids: []
  end
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < ApplicationController
  before_action :logged_in_user, :require_super
  before_action :set_course, except: [:index, :new, :create]
  
  def index
    @courses = Course.paginate page: params[:page], per_page: 20
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params
    if @course.save
      flash[:success] = t(:created_course)
      redirect_to supervisor_course_path(@course)
    else
      render 'new'
    end
  end

  def show
    @course = Course.find params[:id]
  end

  def edit
  end

  def update
    if @course.update_attributes course_params
      flash[:success] = t(:updated_course)
      redirect_to supervisor_course_path(@course)
    else
      flash[:danger] = t(:update_failed)
      render 'edit'
    end
  end

  def destroy
    @course.destroy
    flash[:success] = t(:deleted_course)
    redirect_to supervisor_courses_path
  end
  
  private
  def set_course
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit :course_code, :name, :instruction, subject_ids: []
  end
end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < ApplicationController
  before_action :logged_in_user, :require_super
  
  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t(:subject_created)
      redirect_to @subject
    else
      render 'new'
    end
  end

  def update
    @subject = Subject.find params[:id]
    if @subject.update_attributes subject_params
      flash[:success] = t(:subject_updated)
      redirect_to @subject
    else
      render 'edit'
    end
  end

  def edit
    @subject = Subject.find params[:id]
  end

  def destroy
    Subject.find(params[:id]).destroy
    flash[:success] = t(:subject_deleted)
    redirect_to supervisor_courses_path
  end

  private
  def subject_params
    params.require(:subject).permit :name, :instruction, tasks_attributes: [:id, :title, :content]
  end
end

app/controllers/supervisor/user_tasks_controller.rb
class Supervisor::UserTasksController < ApplicationController
  def update
    @task_id = params[:task_id]
    @user_id = current_user.id
    @var = UserTask.find_by user_id: @user_id, task_id: @task_id
    @var.update_attributes status: t(:complete)
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    respond_to do |format|
      if @user.save
        format.json {head :no_content}
        format.js
      else
        format.json {render json: @user.errors.full_messages, 
                            status: :unprocessable_entity}
      end
    end
  end
 
  def edit
  end
 
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.json {head :no_content}
        format.js
      else
        format.json {render json: @user.errors.full_messages,
                                   status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @user.destroy!
    respond_to do |format|
      format.js
      format.html {redirect_to users_url}
      format.json {head :no_content}
    end
  end

  private
  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
                                 :password_confirmation, :supervisor
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  
  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def show
    @user = User.find params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/supervisor/users/_details.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

app/views/supervisor/users/_dialog.html.erb
<div class="modal fade" id="dialog" tabindex="-1" role="dialog" 
     aria-labelledby="myModalLabel" aria-hidden="true" 
     data-backdrop="static" data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>

      <div class="modal-body">
      </div>
      
    </div>
  </div>
</div>

app/views/supervisor/users/_form.html.erb
<%= form_for [:supervisor, @user], remote: true, html: {role: "form"} do |f| %>
  <div id="error_explanation" class="bg-danger text-danger">
  </div>
  
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :name, class: "control-label" %>
        <%= f.text_field :name, class: "form-control first_input" %>
      </div>
      <div class="form-group">
        <%= f.label :email, class: "control-label" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, class: "control-label" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, class: "control-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :supervisor, "Supervisor?", class: "control-label" %>
        <%= f.check_box :supervisor, class: "control-label" %>
      </div>

      <div class="form-group">
        <%= f.submit @user.new_record? ? "Create User" : "Update User", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/supervisor/users/_user.html.erb
<tr id="user_<%= user.id %>">
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td>
    <%= link_to t(:details_link), supervisor_user_path(user), remote: true %>

    | <%= link_to t(:edit_link), edit_supervisor_user_path(user), remote: true %>

    | <%= link_to t(:delete_link), supervisor_user_path(user), method: :delete, remote: true, data: {confirm: t(:confirm_notification)} %>
  </td>
</tr>

app/views/supervisor/users/create.js.erb
$('#dialog').modal('toggle');
$('#users').append('<%= j render (@user) %>')

app/views/supervisor/users/destroy.js.erb
$('#user_<%= @user.id %>').fadeOut();

app/views/supervisor/users/edit.html.erb
<% provide :title, t(:edit_user) %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/supervisor/users/edit.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-pencil'></i> Edit User");
 
$('.modal-body').html('<%= j render("form") %>');
 
$('#dialog').modal("show");
 
$('#dialog').on('shown.bs.modal', function() {
  $('.first_input').focus()
})

app/views/supervisor/users/index.html.erb
<div class="container">
 
  <h2>All Users</h2>
  
  <div class="well">
    <%= link_to "New User", new_supervisor_user_path, remote: true, class: "btn btn-primary" %>
  </div>

  <div class="new-user"></div>
  
  <%= will_paginate %>
  <table id class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody id="users">
      <%= render @users %>
    </tbody>
  </table>
 
  <%= render 'dialog' %>
</div>

app/views/supervisor/users/new.html.erb
<% provide :title, t(:new_user) %>
<h1>New user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/supervisor/users/new.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New User");
 
$('.modal-body').html('<%= j render("form") %>');
 
$('#dialog').modal("show");
 
$('#dialog').on('shown.bs.modal', function() {
  $('.first_input').focus()
})

app/views/supervisor/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<div class="col-md-8">
  <% if @user.activities.any? %>
    <h3> Activities <%= @user.activities.count %></h3>
    <% @user.activities.each do |activity| %>
      <ol class="row">
        <%= activity.action %>
        <%= activity.find_name %>
      </ol>
    <% end %>
  <% end %>
</div>

app/views/supervisor/users/show.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Details");
 
$('.modal-body').html('<%= j render("details") %>');
 
$('#dialog').modal("show");

app/views/supervisor/users/update.js.erb
$('#dialog').modal('toggle');
$('#user_<%= @user.id %>').replaceWith('<%= j render (@user) %>')