config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:index, :show]
  resources :subjects, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :user_tasks, only: :update
  resources :user_subjects, only: :update

  namespace :supervisor do
    resources :users
    
    resources :courses do
      resource :assign_trainees
    end

    resources :subjects do
      resources :tasks
    end
    root 'users#index'
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :course_subjects, dependent: :destroy
  has_many :courses, through: :course_subjects
  has_many :tasks, dependent: :destroy
  has_many :user_subjects

  accepts_nested_attributes_for :tasks, reject_if: lambda {|a| a[:content].blank?}, allow_destroy: true
  
  validates :name, presence: true
  validates :instruction, presence: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :logged_in_user
  
  def show
    @subject = Subject.find params[:id]
  end
end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < ApplicationController
  before_action :logged_in_user, :require_super
  
  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t(:subject_created)
      redirect_to @subject
    else
      render 'new'
    end
  end

  def update
    @subject = Subject.find params[:id]
    if @subject.update_attributes subject_params
      flash[:success] = t(:subject_updated)
      redirect_to @subject
    else
      render 'edit'
    end
  end

  def edit
    @subject = Subject.find params[:id]
  end

  def destroy
    Subject.find(params[:id]).destroy
    flash[:success] = t(:subject_deleted)
    redirect_to supervisor_courses_path
  end

  private
  def subject_params
    params.require(:subject).permit :name, :instruction, tasks_attributes: [:id, :title, :content]
  end
end

app/views/subjects/_subject.html.erb
<li>
  <h4><%= link_to subject.name, subject%></h4>
  <%= subject.start_date %>
  <%= subject.end_date %>
</li>

app/views/subjects/index.html.erb
<% provide :title, 'All Courses' %>
<h1>Subjects</h1>
<%= will_paginate %>
<li class="subject" >
  <% @subjects.each do |subject| %>
    <%= render subject %>
    <%= link_to "view", supervisor_subject_path(subject) %>
  <% end %>
</li>
<%= will_paginate %>

app/views/subjects/show.html.erb
<% provide :title, @subject.name %>
<div class="panel panel-info">
  <div class="alert alert-info" role="alert"><span class="user">
    <h3><%= link_to @subject.name, @subject %></h3>
    <span class="timestamp">
      Posted <%= time_ago_in_words @subject.created_at %> ago.
    </span>
    <% user_subject = user_subject current_user.id, @subject.id %>
    <% unless user_subject.status == t(:completed) %>
      <%= link_to t(:finish), user_subject_path(user_subject, status: t(:completed)),
          method: :patch, remote: true, class: "user-subject-status btn btn-primary" %>
    <% end %>
  </div>
  <span class="content">
    <%= @subject.instruction %>
  </span>
</div>
<%= render @subject.tasks %>